import { Subject } from "rxjs";

export const eventBus = new Subject();

export enum EventTypes {
  NATIVE_TOKEN_BALANCE_CHANGE = "NATIVE_TOKEN_BALANCE_CHANGE",
  ERC20_TOKEN_BALANCE_CHANGE = "ERC20_TOKEN_BALANCE_CHANGE",
  USER_SIGNUP_SHOW_INVITE_CODE_MODEL = "USER_SIGNUP_SHOW_INVITE_CODE_MODEL",
  USER_SIGNUP_CLOSE_INVITE_CODE_MODEL = "USER_SIGNUP_CLOSE_INVITE_CODE_MODEL",
  USER_SIGNUP_SUCCESS = "USER_SIGNUP_SUCCESS",
  USER_SIGNUP_FAIL = "USER_SIGNUP_FAIL",
}
